#!/usr/bin/env python3
"""gen_philosophers_lines.py — emit a FLICKER-FREE dining-philosophers .abcl.

The previous DiningPhilosophers.abcl drew every shape with tri() (filled
polygons).  The Xinu VM-graphics window repaints the WHOLE content rect before
re-drawing fills, so a tri()-based animation visibly flashes every frame.  This
generator draws the scene with line() ONLY, which takes the kernel's
flicker-free incremental path (un-draw last frame's segments, stroke the new
ones — no full clear).

Scene: 5 philosophers on a ring around a round table, 5 forks between them.
  THINK = blue(1)   HUNGRY = yellow(6)   EAT = green(2)
  fork free = gray(8)   fork held = white(15)
An eating philosopher reaches two green "arms" to the two forks it holds, and
those forks slide toward it — so who-holds-what is unambiguous and the motion
reads naturally.  The simulation is deadlock-free (no two adjacent philosophers
eat at once) and starvation-free (a hungry philosopher defers to a hungrier
neighbour — aging), exactly matching the in-kernel diners.

line() colours are palette indices (kernel bas_palette, 16 entries).
"""
import math

# ---- palette indices (must match apps/gwm.c bas_palette) -------------------
C_THINK, C_HUNGRY, C_EAT = 1, 6, 2          # blue / yellow / green
C_TABLE, C_FORK_FREE, C_FORK_HELD = 8, 8, 15
C_PLATE = 3                                  # cyan plate ring

# ---- geometry (VM graphics content coords; window content ~812 x 605) ------
CX, CY = 406, 300
RP = 210        # philosopher ring radius
RD = 46         # philosopher disc radius
RT = 118        # table radius
RF = 150        # fork base radius
PLATE_R = 26    # plate ring radius (in front of each philosopher)

def ang(i):     # philosopher i angle, start at top, clockwise
    return math.radians(-90 + i * 72)
def fang(k):    # fork k angle (between phil k and phil k+1)
    return math.radians(-90 + (k + 0.5) * 72)

def P(i):
    return (CX + RP * math.cos(ang(i)), CY + RP * math.sin(ang(i)))
def plateP(i):  # plate sits between the table edge and the philosopher
    a = ang(i)
    return (CX + (RP - RD - 6) * math.cos(a), CY + (RP - RD - 6) * math.sin(a))

def ring(cx, cy, r, n):
    """n-gon outline as a list of (x1,y1,x2,y2) integer segments."""
    pts = [(cx + r * math.cos(2 * math.pi * j / n),
            cy + r * math.sin(2 * math.pi * j / n)) for j in range(n)]
    segs = []
    for j in range(n):
        x1, y1 = pts[j]; x2, y2 = pts[(j + 1) % n]
        segs.append((round(x1), round(y1), round(x2), round(y2)))
    return segs

def fork_seg(cx, cy, a):
    """a short tangential tick = a fork lying on the table edge, centred (cx,cy)."""
    tx, ty = -math.sin(a), math.cos(a)
    hl = 17
    return (round(cx - tx * hl), round(cy - ty * hl),
            round(cx + tx * hl), round(cy + ty * hl))

def fork_base(k):
    return (CX + RF * math.cos(fang(k)), CY + RF * math.sin(fang(k)))

def fork_held_center(k, towards_i):
    """fork k centre slid 38% toward philosopher `towards_i`."""
    fx, fy = fork_base(k)
    px, py = P(towards_i)
    return (fx + 0.38 * (px - fx), fy + 0.38 * (py - fy))

# ---- per-philosopher simulation timings (staggered for natural variety) ----
THINK = [4, 6, 5, 7, 5]
EAT   = [3, 4, 3, 4, 3]
T0    = [2, 4, 6, 3, 8]   # initial countdowns so they don't all flip together

L = []   # output lines of the .abcl
def emit(s): L.append(s)

emit("// DiningPhilosophers.abcl — 5 dining philosophers, FLICKER-FREE (line-only).")
emit("// Generated by abclc/gen_philosophers_lines.py.  THINK=blue HUNGRY=yellow EAT=green.")
emit("// Deadlock-free (no adjacent eaters) + starvation-free (aging).")
emit("class Diners {")
emit("  // The Xinu VM caps objects at MAX_FIELDS=16, so this class uses EXACTLY")
emit("  // 16 fields (s*,t*,h*,ok = indices 0..15).  A 17th field would read back")
emit("  // as 0 / drop writes on the board (that silently broke eating + colours).")
emit("  var s0=0; var s1=0; var s2=0; var s3=0; var s4=0;     // 0=think 1=hungry 2=eat (idx 0..4)")
emit("  var t0=%d; var t1=%d; var t2=%d; var t3=%d; var t4=%d;   // countdown timers (idx 5..9)" % tuple(T0))
emit("  var h0=0; var h1=0; var h2=0; var h3=0; var h4=0;     // hunger age, fairness (idx 10..14)")
emit("  var ok=0;                                             // eat-decision temp (idx 15)")
emit("")
emit("  // field initialisers above are not honoured by the AVM backend (zero-init),")
emit("  // so run() sets the staggered countdowns explicitly before the frame loop.")
emit("  method run() { t0=%d; t1=%d; t2=%d; t3=%d; t4=%d; send self.frame(); }" % tuple(T0))
emit("")
emit("  method frame() {")
emit("    cls();")

# --- simulation update (unrolled) ---
emit("    // ---- advance the simulation one tick ----")
for i in range(5):
    Ln, Rn = (i + 4) % 5, (i + 1) % 5
    emit("    if (s%d == 0) { t%d = t%d - 1; if (t%d < 1) { s%d = 1; h%d = 0; } }"
         % (i, i, i, i, i, i))
    emit("    if (s%d == 1) {" % i)
    emit("      h%d = h%d + 1;" % (i, i))
    emit("      if (s%d < 2) { if (s%d < 2) {" % (Ln, Rn))
    emit("        ok = 1;")
    emit("        if (s%d == 1) { if (h%d < h%d) { ok = 0; } }" % (Ln, i, Ln))
    emit("        if (s%d == 1) { if (h%d < h%d) { ok = 0; } }" % (Rn, i, Rn))
    emit("        if (ok == 1) { s%d = 2; t%d = %d; }" % (i, i, EAT[i]))
    emit("      } }")
    emit("    }")
    emit("    if (s%d == 2) { t%d = t%d - 1; if (t%d < 1) { s%d = 0; t%d = %d; } }"
         % (i, i, i, i, i, i, THINK[i]))

# --- table ---
emit("    // ---- round table ----")
for (x1, y1, x2, y2) in ring(CX, CY, RT, 20):
    emit("    line(%d,%d,%d,%d,%d);" % (x1, y1, x2, y2, C_TABLE))

# --- forks ---
emit("    // ---- forks (slide to whichever neighbour is eating) ----")
for k in range(5):
    a = fang(k)
    fx, fy = fork_base(k)
    free = fork_seg(fx, fy, a)
    kc = fork_held_center(k, k)
    k1c = fork_held_center(k, (k + 1) % 5)
    heldk = fork_seg(kc[0], kc[1], a)
    heldk1 = fork_seg(k1c[0], k1c[1], a)
    # no temp flag (field budget): held forks draw when a neighbour eats; the free
    # fork draws only when NEITHER neighbour eats (state < 2 == not eating).
    emit("    if (s%d == 2) { line(%d,%d,%d,%d,%d); }"
         % (k, heldk[0], heldk[1], heldk[2], heldk[3], C_FORK_HELD))
    emit("    if (s%d == 2) { line(%d,%d,%d,%d,%d); }"
         % ((k + 1) % 5, heldk1[0], heldk1[1], heldk1[2], heldk1[3], C_FORK_HELD))
    emit("    if (s%d < 2) { if (s%d < 2) { line(%d,%d,%d,%d,%d); } }"
         % (k, (k + 1) % 5, free[0], free[1], free[2], free[3], C_FORK_FREE))

# --- philosophers: disc (state colour) + plate + eating arms ---
emit("    // ---- philosophers: disc colour = state, arms reach forks when eating ----")
for i in range(5):
    px, py = P(i)
    px, py = round(px), round(py)
    disc = ring(px, py, RD, 8)
    plx, ply = plateP(i); plx, ply = round(plx), round(ply)
    plate = ring(plx, ply, PLATE_R, 6)
    # arms: from disc centre to the two forks this philosopher holds when eating
    Lf, Rf_ = (i + 4) % 5, i          # phil i holds fork[(i+4)%5] and fork[i]
    aL = fork_held_center(Lf, i)
    aR = fork_held_center(Rf_, i)
    # disc colour = state, drawn with literal palette indices in three guarded
    # blocks (no `col` temp field — the VM only has 16 field slots).
    for st, c in ((0, C_THINK), (1, C_HUNGRY), (2, C_EAT)):
        emit("    if (s%d == %d) {" % (i, st))
        for (x1, y1, x2, y2) in disc:
            emit("      line(%d,%d,%d,%d,%d);" % (x1, y1, x2, y2, c))
        emit("    }")
    for (x1, y1, x2, y2) in plate:
        emit("    line(%d,%d,%d,%d,%d);" % (x1, y1, x2, y2, C_PLATE))
    emit("    if (s%d == 2) {" % i)
    emit("      line(%d,%d,%d,%d,%d);" % (px, py, round(aL[0]), round(aL[1]), C_EAT))
    emit("      line(%d,%d,%d,%d,%d);" % (px, py, round(aR[0]), round(aR[1]), C_EAT))
    emit("    }")

# --- legend: three small swatches top-left ---
emit("    // ---- legend swatches: think / hungry / eat ----")
for j, c in enumerate((C_THINK, C_HUNGRY, C_EAT)):
    y = 16 + j * 22
    for (x1, y1, x2, y2) in ring(26, y + 8, 9, 4):
        emit("    line(%d,%d,%d,%d,%d);" % (x1, y1, x2, y2, c))

emit("    wait(150);")
emit("    send self.frame();")
emit("  }")
emit("}")
emit("")
emit("var d = new Diners();")
emit("send d.run();")

out = "\n".join(L) + "\n"
import sys, os
dest = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "DiningPhilosophers.abcl")
with open(dest, "w") as f:
    f.write(out)
print("wrote %s (%d lines)" % (dest, len(L)))
