// gen_philosophers.mjs — the 5 dining philosophers as a self-looping AIPL actor.
//
// 5 philosophers + 5 forks modelled in one AIPL actor.  Each philosopher cycles
// THINK -> HUNGRY -> EAT -> THINK with its own timer; a hungry philosopher only
// starts eating when NEITHER neighbour is eating (so adjacent philosophers never
// hold the same fork => no deadlock).  The simulation runs LIVE each frame (not
// baked), then the frame is drawn with cls()/line(...,0)/tri(...,RGB) so the SAME
// source renders in the browser AIPL runtime AND compiles to a portable .avm:
//   aipl2c.exe --avm --no-typecheck abclc/DiningPhilosophers.abcl -o abclc/DiningPhilosophers.avm
//
// Run:  node gen_philosophers.mjs > abclc/DiningPhilosophers.abcl
import { writeFileSync } from "node:fs";

// ---- geometry: target the Xinu VM window (760x620) so it fits on-board ----
const W = 760, H = 620, CX = 380, CY = 300;
const R_PHIL = 200;          // philosopher ring radius (pushed back a little)
const R_FORK = 162;          // fork ring radius — OUTSIDE the table so forks/arrows aren't buried
const DISC   = 46;           // philosopher disc radius
const PLATE  = 26;           // plate radius
const TABLE  = 140;          // table radius (smaller than the fork ring)
const D2R = Math.PI / 180;

// colours (0xRRGGBB)
const C = {
  think: 0x4d7fff, hungry: 0xffb45a, eat: 0x57e07a,
  table: 0x243447, tableHi: 0x2f4458, plate: 0xc9d6e6,
  forkFree: 0x6c7a8a, forkHeld: 0xffe14d, head: 0xe8eef6,
};

const N = 5;
const ang = (i) => -90 + i * (360 / N);                 // philosopher i angle (deg)
const px  = (i) => Math.round(CX + R_PHIL * Math.cos(ang(i) * D2R));
const py  = (i) => Math.round(CY + R_PHIL * Math.sin(ang(i) * D2R));
const fx  = (i) => Math.round(CX + R_FORK * Math.cos((ang(i) + 36) * D2R));  // fork between i,i+1
const fy  = (i) => Math.round(CY + R_FORK * Math.sin((ang(i) + 36) * D2R));

// octagon offsets for a disc of radius r (8 verts)
function octa(r, squash = 1) {
  const p = [];
  for (let k = 0; k < 8; k++) {
    const t = (k / 8) * 2 * Math.PI;
    p.push([Math.round(Math.cos(t) * r), Math.round(Math.sin(t) * r * squash)]);
  }
  return p;
}

let out = [];
const L = (s) => out.push(s);

// thick segment as two RGB triangles (line() treats colour as a palette index,
// so use tri() for true colours).  colExpr may be a literal int or the field "col".
function seg(x1, y1, x2, y2, colExpr, wpx = 5, indent = "    ") {
  const dx = x2 - x1, dy = y2 - y1, len = Math.hypot(dx, dy) || 1;
  const px = Math.round((-dy / len) * (wpx / 2)), py = Math.round((dx / len) * (wpx / 2));
  const a = [x1 + px, y1 + py], b = [x2 + px, y2 + py], c = [x2 - px, y2 - py], d = [x1 - px, y1 - py];
  return [
    `${indent}tri(${a[0]},${a[1]},${b[0]},${b[1]},${c[0]},${c[1]},${colExpr});`,
    `${indent}tri(${a[0]},${a[1]},${c[0]},${c[1]},${d[0]},${d[1]},${colExpr});`,
  ];
}

// --- header / class / fields ---
L(`// DiningPhilosophers.abcl — the 5 dining philosophers as a live AIPL actor.`);
L(`// 5 philosophers (sN: 0=THINK 1=HUNGRY 2=EAT) + 5 forks, simulated each frame`);
L(`// with a no-adjacent-eaters rule (deadlock-free), drawn with cls()/line/tri so`);
L(`// it renders in the browser AND compiles to a portable .avm.  Generated by`);
L(`// abclc/gen_philosophers.mjs.  Colours: blue=think amber=hungry green=eat.`);
L(`class Diners {`);
L(`  // field 0 must be a MONOTONIC frame counter: the Xinu VM treats field 0 as a`);
L(`  // turntable frame index and, if it ever decreases, switches to replaying a few`);
L(`  // cached frames (=flicker).  A never-wrapping counter keeps it in LIVE mode.`);
L(`  var fctr = 0;`);
L(`  var s0 = 0; var s1 = 0; var s2 = 0; var s3 = 0; var s4 = 0;   // state 0=think 1=hungry 2=eat`);
L(`  var t0 = 2; var t1 = 4; var t2 = 6; var t3 = 3; var t4 = 8;   // think/eat timers (staggered)`);
L(`  var h0 = 0; var h1 = 0; var h2 = 0; var h3 = 0; var h4 = 0;   // hunger age (frames spent hungry)`);
L(`  var ok = 0;`);
L(`  var col = 0;`);
L(``);
L(`  method run() { send self.frame(); }`);
L(``);
L(`  method frame() {`);
L(`    cls();`);

// --- table (octagon fan, dark) ---
const to = octa(TABLE, 0.82);
for (let k = 0; k < 8; k++) {
  const n = (k + 1) % 8;
  const shade = (k < 4) ? C.table : C.tableHi;
  L(`    tri(${CX},${CY},${CX + to[k][0]},${CY + to[k][1]},${CX + to[n][0]},${CY + to[n][1]},${shade});`);
}

// --- simulation step (unrolled, sequential; THINK/EAT durations per philosopher) ---
const THINK = [4, 6, 5, 7, 5], EAT = [3, 4, 3, 5, 4];
const left = (i) => (i + N - 1) % N, right = (i) => (i + 1) % N;
L(`    // --- advance the simulation one step ---`);
L(`    // deadlock-free: eat only if NEITHER neighbour is eating;`);
L(`    // starvation-free: a hungry philosopher yields to a hungry neighbour that has`);
L(`    // been waiting at least as long (aging) -> the longest-waiting one always eats.`);
for (let i = 0; i < N; i++) {
  const s = `s${i}`, t = `t${i}`, h = `h${i}`;
  const sl = `s${left(i)}`, sr = `s${right(i)}`, hl = `h${left(i)}`, hr = `h${right(i)}`;
  L(`    if (${s} == 0) { ${t} = ${t} - 1; if (${t} < 1) { ${s} = 1; ${h} = 0; } }`);
  L(`    if (${s} == 1) {`);
  L(`      ${h} = ${h} + 1;`);
  L(`      if (${sl} < 2) { if (${sr} < 2) {`);
  L(`        ok = 1;`);
  L(`        if (${sl} == 1) { if (${h} < ${hl}) { ok = 0; } }`);   // left hungry & waiting longer -> yield
  L(`        if (${sr} == 1) { if (${h} < ${hr}) { ok = 0; } }`);   // right hungry & waiting longer -> yield
  L(`        if (ok == 1) { ${s} = 2; ${t} = ${EAT[i]}; }`);
  L(`      } }`);
  L(`    }`);
  L(`    if (${s} == 2) { ${t} = ${t} - 1; if (${t} < 1) { ${s} = 0; ${t} = ${THINK[i]}; } }`);
}

// --- forks (between philosopher i and i+1): held (yellow) if either eats, else grey ---
// An ARROW points from the fork to the philosopher currently holding it (adjacent
// philosophers never eat together, so at most one holds each fork).
const ARROW = 0xffd23c;                                 // arrow colour (gold)
function arrowCmds(fxp, fyp, tx, ty) {
  const dx = tx - fxp, dy = ty - fyp, len = Math.hypot(dx, dy) || 1;
  const ux = dx / len, uy = dy / len, pxp = -uy, pyp = ux;
  const tipx = Math.round(tx - ux * (DISC + 4)), tipy = Math.round(ty - uy * (DISC + 4));
  const sx = Math.round(fxp + ux * 8), sy = Math.round(fyp + uy * 8);
  const bx = Math.round(tipx - ux * 15), by = Math.round(tipy - uy * 15), hw = 9;
  const b1x = Math.round(bx + pxp * hw), b1y = Math.round(by + pyp * hw);
  const b2x = Math.round(bx - pxp * hw), b2y = Math.round(by - pyp * hw);
  return [
    ...seg(sx, sy, bx, by, ARROW, 4, "      "),       // shaft (RGB tri, not line)
    `      tri(${tipx},${tipy},${b1x},${b1y},${b2x},${b2y},${ARROW});`,  // head
  ];
}
L(`    // --- forks: held if an adjacent philosopher is eating; arrow -> the holder ---`);
for (let i = 0; i < N; i++) {
  const j = right(i);
  // draw a short fork segment radiating at the fork position, coloured by held state
  L(`    col = ${C.forkFree};`);
  L(`    if (s${i} == 2) { col = ${C.forkHeld}; }`);
  L(`    if (s${j} == 2) { col = ${C.forkHeld}; }`);
  const fxA = Math.round(CX + (R_FORK - 22) * Math.cos((ang(i) + 36) * D2R));
  const fyA = Math.round(CY + (R_FORK - 22) * Math.sin((ang(i) + 36) * D2R));
  const fxB = Math.round(CX + (R_FORK + 26) * Math.cos((ang(i) + 36) * D2R));
  const fyB = Math.round(CY + (R_FORK + 26) * Math.sin((ang(i) + 36) * D2R));
  for (const c of seg(fxA, fyA, fxB, fyB, "col", 6)) L(c);
  // arrow toward whichever neighbour currently holds this fork
  const fc = [fx(i), fy(i)];
  L(`    if (s${i} == 2) {`);
  for (const c of arrowCmds(fc[0], fc[1], px(i), py(i))) L(c);
  L(`    }`);
  L(`    if (s${j} == 2) {`);
  for (const c of arrowCmds(fc[0], fc[1], px(j), py(j))) L(c);
  L(`    }`);
}

// --- philosophers (plate + state disc + head dot) ---
const od = octa(DISC, 0.92);
const opl = octa(PLATE, 0.6);
L(`    // --- philosophers: plate + disc coloured by state (blue/amber/green) ---`);
for (let i = 0; i < N; i++) {
  const x = px(i), y = py(i);
  // plate (light ellipse, slightly below the philosopher toward the table)
  const plx = Math.round(CX + (R_PHIL - 70) * Math.cos(ang(i) * D2R));
  const ply = Math.round(CY + (R_PHIL - 70) * Math.sin(ang(i) * D2R));
  for (let k = 0; k < 8; k++) {
    const nn = (k + 1) % 8;
    L(`    tri(${plx},${ply},${plx + opl[k][0]},${ply + opl[k][1]},${plx + opl[nn][0]},${ply + opl[nn][1]},${C.plate});`);
  }
  // state colour
  L(`    col = ${C.think};`);
  L(`    if (s${i} == 1) { col = ${C.hungry}; }`);
  L(`    if (s${i} == 2) { col = ${C.eat}; }`);
  for (let k = 0; k < 8; k++) {
    const nn = (k + 1) % 8;
    L(`    tri(${x},${y},${x + od[k][0]},${y + od[k][1]},${x + od[nn][0]},${y + od[nn][1]},col);`);
  }
  // head dot (so they look like seated diners)
  const ho = octa(14, 0.95);
  const hx = Math.round(CX + (R_PHIL + 30) * Math.cos(ang(i) * D2R));
  const hy = Math.round(CY + (R_PHIL + 30) * Math.sin(ang(i) * D2R));
  for (let k = 0; k < 8; k++) {
    const nn = (k + 1) % 8;
    L(`    tri(${hx},${hy},${hx + ho[k][0]},${hy + ho[k][1]},${hx + ho[nn][0]},${hy + ho[nn][1]},${C.head});`);
  }
}

// --- legend swatches (top-left): think / hungry / eat ---
const sw = (x, y, c) => {
  L(`    tri(${x},${y},${x + 22},${y},${x + 22},${y + 16},${c});`);
  L(`    tri(${x},${y},${x + 22},${y + 16},${x},${y + 16},${c});`);
};
L(`    // legend: think / hungry / eat`);
sw(16, 16, C.think); sw(16, 40, C.hungry); sw(16, 64, C.eat);

// --- frame end ---
L(`    fctr = fctr + 1;`);   // advance the (monotonic) frame counter -> stay in live render mode
L(`    wait(150);`);
L(`    send self.frame();`);
L(`  }`);
L(`}`);
L(``);
L(`var d = new Diners();`);
L(`send d.run();`);
L(``);

const dest = process.argv[2] || "/dev/stdout";
writeFileSync(dest, out.join("\n"));
process.stderr.write(`wrote ${dest}: ${out.length} lines\n`);
