(ocamllex (modules lexer))
(ocamlyacc (modules parser))

(library
 (name abcllib)
 (wrapped false)
 (modules
  ast
  location
  types
  typing_env
  infer
  typecheck
  sdl_helper
  hmac_sha256
  remote_client
  parser
  lexer
  eval_thread
  compiler
  c_translator
  avm_gen
  web_gateway
  ai
  aipl_dist
  refinement)
 (flags (:standard -w -a))
 (libraries tsdl threads unix))

(executable
 (name repl_thread)
 (modules repl_thread)
 (flags (:standard -w -a))
 (libraries abcllib tsdl threads unix))

(executable
 (name tui_ide)
 (modules tui_ide)
 (flags (:standard -w -a))
 (libraries unix threads))

(executable
 (name gui_ide)
 (modules gui_ide gui_font)
 (flags (:standard -w -a))
 (libraries abcllib tsdl threads unix))

(executable
 (name aipl2c)
 (modules aipl2c)
 (flags (:standard -w -a))
 (libraries abcllib))

(executable
 (name test_aipl_dist)
 (modules test_aipl_dist)
 (flags (:standard -w -a))
 (libraries abcllib str unix threads))

(executable
 (name test_refine_check)
 (modules test_refine_check)
 (flags (:standard -w -a))
 (libraries abcllib unix))

(executable
 (name test_o2d_inference)
 (modules test_o2d_inference)
 (flags (:standard -w -a))
 (libraries abcllib))
